{% set name = "geowombat" %}
{% set version = "2.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jgrss/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: fecff8796b21351b1d6893c44ba5d944f118cb1d49ee79570a1de4345202760a

build:
  number: 1
  skip: true  # [py<38]
  script: {{ PYTHON }} setup.py build && pip install .

requirements:
  build:
     - {{ compiler('c') }}
  host:
    - python >=3.7,<=3.9.16
    - setuptools >=59.5.0
    - wheel
    - cython >=0.29.0,<3.0.0
    - numpy >=1.19.0
    - pip

  run:
  - python
  - dask-core >=2023.1.0
  - distributed >=2023.1.0
  - geopandas >=0.8.0
  - joblib >=0.16.0
  - matplotlib-base >=3.3.0
  - pandas >=1.0.0
  - pyproj >=3.0.0,<=3.4.0
  - rasterio >=1.3.0,<2.0.0
  - retry
  - requests >=2.20.0
  - scikit-learn >=0.23.0
  - scipy >=1.5.0
  - shapely >=1.7.0
  - tqdm >=4.62.0
  - xarray >=2023.1.0
  - h5netcdf >=1.0.2
  - cryptography >=38.0.0
  - threadpoolctl >=3.1.0
  - setuptools >=59.5.0
  - cython >=0.29.0,<3.0.0
  - {{ pin_compatible('numpy') }}



test:
  imports:
    - geowombat

about:
  home: https://github.com/jgrss/geowombat
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: GeoWombat provides utilities to process geospatial raster data.
  doc_url: https://geowombat.readthedocs.io/
  dev_url: https://github.com/jgrss

extra:
  recipe-maintainers:
    - mxr-conda
    - jgrss
    - mmann1123
