{% set name = "geowombat" %}
{% set version = "2.1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jgrss/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 44485442a98030d513f73dbeb7a34fef81754fbd25ceffe1a53346be7787b27d


build:
  number: 1
  skip: true  # [py<37 or py>310]
  script: {{ PYTHON }} setup.py build && pip install .

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=0.29.0,<3.0.0                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}

  host:
    - python      
    - setuptools >=59.5.0
    - wheel
    - cython >=0.29.0,<3.0.0
    - numpy
    - pip


  run:
    - {{ pin_compatible('python') }}
    - python
    - dask-core >=2023.1.0
    - distributed >=2023.1.0
    - geopandas >=0.8.0
    - joblib >=0.16.0
    - matplotlib-base >=3.3.0
    - pandas >=1.0.0
    - pyproj >=3.0.0,<=3.4.0
    - rasterio >=1.3.0,<2.0.0
    - retry
    - requests >=2.20.0
    - scikit-learn >=0.23.0
    - scipy >=1.5.0
    - shapely >=1.7.0
    - tqdm >=4.62.0
    - xarray >=2023.1.0
    - h5netcdf >=1.0.2
    - cryptography >=38.0.0
    - threadpoolctl >=3.1.0
    - setuptools >=59.5.0
    - cython >=0.29.0,<3.0.0
    - jax  # [not win]
    - ray-default  # [not osx]
    - testfixtures
    - numpy >=1.19.0


test:
  imports:
    - geowombat
  requires:
    - pytest
  source_files:
    - tests
  commands:
      #- pytest tests   #RUN ALL TESTS 
      - pytest tests/test_clip.py
      - pytest tests/test_config.py
      # - pytest tests/test_conreg.py
      - pytest tests/test_extract.py
      - pytest tests/test_gdal.py
      - pytest tests/test_moving.py
    # temp files not compatible with windows ??
      - pytest tests/test_nodata.py  # [not win]
      - pytest tests/test_open.py
      - pytest tests/test_properties.py
    # - pytest tests/test_rad.py  # [not py==38 or not py==39]
      - pytest tests/test_rasterio.py  # [not win]
      - pytest tests/test_scaling.py
      # - pytest tests/test_series.py  # [not win] only in test options
      - pytest tests/test_sops.py
      - pytest tests/test_vi.py
      - pytest tests/test_write.py  # [not win]
      - pytest tests/test_xarray.py

outputs:
    - name: geowombat
      requirements:
        build:
          - python                                 # [build_platform != target_platform]
          - cross-python_{{ target_platform }}     # [build_platform != target_platform]
          - cython >=0.29.0,<3.0.0                 # [build_platform != target_platform]
          - numpy                                  # [build_platform != target_platform]
          - {{ compiler('c') }}

        host:
          - python      
          - setuptools >=59.5.0
          - wheel
          - cython >=0.29.0,<3.0.0
          - numpy
          - pip

        run:
          - {{ pin_compatible('python') }}
          - python 
          - dask-core >=2023.1.0
          - distributed >=2023.1.0
          - geopandas >=0.8.0
          - joblib >=0.16.0
          - matplotlib-base >=3.3.0
          - pandas >=1.0.0
          - pyproj >=3.0.0,<=3.4.0
          - rasterio >=1.3.0,<2.0.0
          - retry
          - requests >=2.20.0
          - scikit-learn >=0.23.0
          - scipy >=1.5.0
          - shapely >=1.7.0
          - tqdm >=4.62.0
          - xarray >=2023.1.0
          - h5netcdf >=1.0.2
          - cryptography >=38.0.0
          - threadpoolctl >=3.1.0
          - setuptools >=59.5.0
          - cython >=0.29.0,<3.0.0
          - testfixtures
          - numpy >=1.19.0

      test:
        imports:
          - geowombat
        requires:
          - pytest
        source_files:
          - tests
        commands:
          #- pytest tests   #RUN ALL TESTS 
          - pytest tests/test_clip.py
          - pytest tests/test_config.py
          - pytest tests/test_conreg.py
          - pytest tests/test_extract.py
          - pytest tests/test_gdal.py
          - pytest tests/test_moving.py
        # temp files not compatible with windows ??
          - pytest tests/test_nodata.py  # [not win]
          - pytest tests/test_open.py
          - pytest tests/test_properties.py
        # - pytest tests/test_rad.py  # [not py==38 or not py==39]
          - pytest tests/test_rasterio.py  # [not win]
          - pytest tests/test_scaling.py
          # - pytest tests/test_series.py  # [not win] only in test options
          - pytest tests/test_sops.py
          - pytest tests/test_vi.py
          - pytest tests/test_write.py  # [not win]
          - pytest tests/test_xarray.py
          


    - name: geowombat-coreg
      requirements:
        host:
          - python
        run:
          - python 
          - {{ pin_subpackage('geowombat', exact=True) }}
          - earthpy
          - pyfftw ==0.13.1
          - bottleneck
          - cartopy
          - cmocean
          - dill
          - geoarray >=0.15.0
          - geojson
          - folium >=0.6.0,!=0.12.0
          - pykrige
          - arosics
          - py-tools-ds  
      test:
        imports:
          - geowombat
        requires:
          - pytest
        source_files:
          - tests
        commands:
          - pytest tests/test_coreg.py  # [not win] 


    - name: geowombat-docs
      requirements:
        host:
          - python
        run:
          - python 
          - {{ pin_subpackage('geowombat', exact=True) }}
          - numpydoc
          - sphinx
          - sphinx-automodapi
          - sphinxcontrib-bibtex <2.0.0
          #- sphinx_tabs
          - pydata-sphinx-theme ==0.13.1
          - sphinx-book-theme >=1.0.0
          - sphinx-copybutton >=0.5.0
          - sphinx-autodoc-typehints
          - ipython
      test:
        imports:
          - geowombat

    - name: geowombat-ml
      requirements:
        host:
          - python
        run:
          - python 
          - {{ pin_subpackage('geowombat', exact=True) }}
          #- numba #>=0.51.0   just added as test can drop
          - lightgbm
          - gw-sklearn-xarray  
      test:
        imports:
          - geowombat
        requires:
          - pytest
        source_files:
          - tests
        commands:
          - pytest tests/test_ml.py
          

    - name: geowombat-perf
      requirements:
        host:
          - python
        run:
          - python 
          - {{ pin_subpackage('geowombat', exact=True) }}
          - rtree
          - pygeos
          - netCDF4
          - ray-default >=2.3.0  # [not osx] 
      test:
        imports:
          - geowombat

    - name: geowombat-stac
      requirements:
        host:
          - python
        run:
          - python 
          - {{ pin_subpackage('geowombat', exact=True) }}
          - stackstac  
          - pystac-client
          - sat-search
          - planetary-computer
          - Rich
          - wget  # [not win]  
      test:
        imports:
          - geowombat


    - name: geowombat-tests  # [not osx and py==38 or not lnx and py==38 or not win] 
      requirements:
        host:
          - python
        run:
          - python 
          - {{ pin_subpackage('geowombat', exact=True) }}
          - testfixtures
          - jax  # [not win]
          - jaxlib  # [not win]
          - pre-commit
          - black
          - flake8
          - docformatter
          - isort   
      test:
        imports:
          - geowombat
      test:
        imports:
          - geowombat
        requires:
          - pytest
        source_files:
          - tests
        commands:
          - pytest tests/test_series.py  # [not win]


    - name: geowombat-view
      requirements:
        host:
          - python
        run:
          - python 
          - {{ pin_subpackage('geowombat', exact=True) }}
          - bokeh
          - descartes  
      test:
        imports:
          - geowombat

    - name: geowombat-view
      requirements:
        host:
          - python
        run:
          - python 
          - {{ pin_subpackage('geowombat', exact=True) }}
          - gsutil
          - requests  
      test:
        imports:
          - geowombat

    - name: geowombat-web
      requirements:
        host:
          - python
        run:
          - python 
          - {{ pin_subpackage('geowombat', exact=True) }}
          - gsutil
          - requests 
      test:
        imports:
          - geowombat


    - name: geowombat-zarr
      requirements:
        host:
          - python
        run:
          - python 
          - {{ pin_subpackage('geowombat', exact=True) }}
          - zarr
          - numcodecs 
      test:
        imports:
          - geowombat

about:
  home: https://github.com/jgrss/geowombat
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: GeoWombat provides utilities to process geospatial raster data.
  doc_url: https://geowombat.readthedocs.io/
  dev_url: https://github.com/jgrss

extra:
  recipe-maintainers:
    - mxr-conda
    - jgrss
    - mmann1123

# notes:
# build in mamba  https://conda-forge.org/docs/maintainer/maintainer_faq.html#mfaq-mamba-local
# build local `python build-locally.py`
# optional extras example https://github.com/conda-forge/ray-packages-feedstock/blob/main/recipe/meta.yaml
#https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html?highlight=subpackages#implicit-metapackages
