{% set name = "geowombat" %}
{% set version = "1.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jgrss/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e6829cba3f4954d35a183ee7f1a34d777c8fb8cc232f2ebe1e1602c9cf6e063f

build:
  number: 0
  script: {{ PYTHON }} setup.py build && pip install .

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libgomp  # [linux]
    - llvm-openmp  # [osx or win]
    - clang         # [win]
  host:
    - pip
    - python
    - gdal
    - cython
    - numpy
    - libgdal
    - proj
  run:
    - cython
    - python
    - matplotlib-base
    - pandas
    - geopandas
    - rasterio
    - xarray
    - dask
    - distributed
    - affine
    - joblib
    - opencv
    - tqdm
    - shapely
    - h5netcdf
    - netCDF4
    - scikit-learn
    - numcodecs
    - zarr
    - dateparser
    - wget  # [not win]
    - fsspec
    - python-graphviz
    - requests
    - retry
    - pyyaml
    - gdal
    - pyamg
    - pyproj
    - {{ pin_compatible('numpy') }}
    - libgdal


test:
  imports:
    - geowombat

about:
  home: https://github.com/jgrss/geowombat
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: GeoWombat provides utilities to process geospatial raster data.
  doc_url: https://geowombat.readthedocs.io/
  dev_url: https://github.com/jgrss

extra:
  recipe-maintainers:
    - mxr-conda
    - jgrss
    - mmann1123
