{% set name = "geowombat" %}
{% set version = "1.8.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jgrss/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: ad160dfdb41b663d9544557e38f1436fa28ca48007a84c8a2c6e30a7d80327dc

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
  host:
    - pip
    - python
    - gdal
    - cython
  run:
    - cython
    - python
    - matplotlib-base
    - pandas
    - geopandas
    - numpy
    - rasterio
    - xarray
    - dask
    - distributed
    - affine
    - joblib
    - opencv
    - tqdm
    - shapely
    - h5netcdf
    - netCDF4
    - scikit-learn
    - numcodecs
    - zarr
    - dateparser
    - wget  # [not win]
    - fsspec
    - python-graphviz
    - requests
    - retry
    - privy
    - pyyaml
    - gdal
    - pyamg
    - pyproj


test:
  imports:
    - geowombat

about:
  home: https://github.com/jgrss/geowombat
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: GeoWombat provides utilities to process geospatial raster data.
  doc_url: https://geowombat.readthedocs.io/
  dev_url: https://github.com/jgrss

extra:
  recipe-maintainers:
    - mxr-conda
    - ndmaxar
    - RyanHackney
    - jgrss
    - mmann1123
    - rluria14
