{% set name = "geowombat" %}
{% set version = "2.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jgrss/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: aa32d8e83f956f45dbc6761bcdd9f9d46745587c8a843085dd8537538a4bd6ff  
    

#skip py controls python version builds
build:
  number: 0
  skip: true  # [py<37 or py>39]
  script: {{ PYTHON }} setup.py build && pip install .

requirements:
  build:
    - {{ compiler('c') }}
    #- python                                 # [build_platform != target_platform]
    #- cross-python_{{ target_platform }}     # [build_platform != target_platform]
    #- cython                                 # [build_platform != target_platform]
    #- clang  # [win]
    #- numpy                                  # [build_platform != target_platform]

  host:
    - python      
    - setuptools >=59.5.0
    - wheel
    - cython >=0.29.0,<3.0.0
    - numpy >=1.19.0
    - pip






outputs:
    - name: geowombat
      requirements:
        build:
          - {{ compiler('c') }}
          - python                                 # [build_platform != target_platform]
          - cross-python_{{ target_platform }}     # [build_platform != target_platform]
          - cython                                 # [build_platform != target_platform]
          - clang  # [win]
          - numpy                                  # [build_platform != target_platform]


        host:
          - python      
          - setuptools >=59.5.0
          - wheel
          - cython >=0.29.0,<3.0.0
          - numpy >=1.19.0
          - pip

        run:
          - {{ pin_compatible('python') }}
          - python 
          - dask-core >=2023.1.0
          - distributed >=2023.1.0
          - geopandas >=0.8.0
          - joblib >=0.16.0
          - matplotlib-base >=3.3.0
          - pandas >=1.0.0
          - pyproj >=3.0.0,<=3.4.0
          - rasterio >=1.3.0,<2.0.0
          - retry
          - requests >=2.20.0
          - scikit-learn >=0.23.0
          - scipy >=1.5.0
          - shapely >=1.7.0
          - tqdm >=4.62.0
          - xarray >=2023.1.0
          - h5netcdf >=1.0.2
          - cryptography >=38.0.0
          - threadpoolctl >=3.1.0
          - setuptools >=59.5.0
          - cython >=0.29.0,<3.0.0
          - jax  # [not win]
        # - sklearn-xarray  
          - testfixtures
          - {{ pin_compatible('numpy') }}

      test:
        imports:
          - geowombat
        requires:
          - pytest
        source_files:
          - tests
        commands:
          #- pytest tests   #RUN ALL TESTS 
          - pytest tests/test_clip.py
          - pytest tests/test_config.py
          # coreg requires 
      #    - pytest tests/test_coreg.py
          - pytest tests/test_dask_cluster.py
          - pytest tests/test_extract.py
          - pytest tests/test_gdal.py
          - pytest tests/test_load.py  # [not osx]
          - pytest tests/test_moving.py
        # temp files not compatible with windows ??
          - pytest tests/test_nodata.py  # [not win]
          - pytest tests/test_open.py
          - pytest tests/test_properties.py
        # - pytest tests/test_rad.py  # [not py==38 or not py==39]
          - pytest tests/test_rasterio.py  # [not win]
          - pytest tests/test_scaling.py
          - pytest tests/test_series.py  # [not win]
          - pytest tests/test_sops.py
          - pytest tests/test_vi.py
          - pytest tests/test_write.py  # [not win]
          - pytest tests/test_xarray.py
          
    - name: geowombat-perf
      requirements:
          - python 
          - rtree
          - pygeos
          - netCDF4
          - ray-default >=2.3.0  # [not osx] 

about:
  home: https://github.com/jgrss/geowombat
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: GeoWombat provides utilities to process geospatial raster data.
  doc_url: https://geowombat.readthedocs.io/
  dev_url: https://github.com/jgrss

extra:
  recipe-maintainers:
    - mxr-conda
    - jgrss
    - mmann1123

# notes:
# build in mamba  https://conda-forge.org/docs/maintainer/maintainer_faq.html#mfaq-mamba-local
# build local `python build-locally.py`
# optional extras example https://github.com/conda-forge/ray-packages-feedstock/blob/main/recipe/meta.yaml
#https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html?highlight=subpackages#implicit-metapackages
