{% set name = "geowombat" %}
{% set version = "1.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/jgrss/{{ name }}/archive/{{ version }}.tar.gz"
  sha256: 9c7026119e6647822a260496cf9064dca36ae333d143f89a82c63c08e90ab51f

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - gdal
    - cython
    - libgdal
    - proj
  run:
    - cython
    - python
    - libgdal
    - matplotlib-base
    - pandas
    - geopandas
    - {{ pin_compatible('numpy') }}
    - rasterio
    - xarray
    - dask
    - dask-ml
    - distributed
    - affine
    - joblib
    - opencv
    - tqdm
    - shapely
    - h5netcdf
    - netCDF4
    - scikit-learn
    - numexpr
    - numcodecs
    - zarr
    - dateparser
    - wget  # [not win]
    - fsspec
    - sphinx-automodapi
    - sphinxcontrib-bibtex
    - numpydoc
    - deprecated
    - proj

test:
  imports:
    - geowombat

about:
  home: "https://github.com/jgrss/geowombat"
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "GeoWombat provides utilities to process geospatial raster data."
  doc_url: https://geowombat.readthedocs.io/
  dev_url: https://github.com/jgrss

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - ndmaxar
    - RyanHackney
